### ISSUE TITLE
Visibility Performance Tracking Issue

### ISSUE THREAD

**Issue by helgee** [lox-space/lox#176]
- [x] Add benchmark and performance tracking #175 
- [x] Refactor enums
  - [x] `TimeScale` #194
  - [x] `Body` #179 
  - [x] `Frame` #179 
- [x] Move looping over asset combinations to Rust side
- [x] Implement line-of-sight for space-to-space and additional bodies
- [x] Parallelise with [rayon](https://github.com/rayon-rs/rayon)
