### ISSUE TITLE
`lox-time` Tracking Issue

### ISSUE THREAD

**Issue by helgee** [lox-space/lox#97]
- [x] Implement parser for NAIF leap seconds kernels in lox-io (#98)
- [x] Implement LeapSecondsProvider trait and BuiltinLeapSeconds/Lsk impls (working title) in lox-time (#99)
- [x] Dismantle lox-eop and move the IERS parser to lox-io and the tidal model to lox-earth (#100)
- [x] Reimplement IERS interpolation based on CubicSpline interpolator (#101)
- [x] Refactor transformations (#102)
- [x] Complete Python API (#103)

CC: @AngusGMorrison
